on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: get latest release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: ${{ github.repository }}
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set releasing version
        run: |
          # remove 'v' prefix from ref name
          echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: echo release info
        run: |
          echo "releasing ref: $GITHUB_REF_NAME"
          echo "releasing version: ${{ env.RELEASE_VERSION }}"
          echo "latest release: ${{ steps.latest-release.outputs.release }}"
      - name: build docker image
        run: |
          make docker-build -e VERSION=${{ env.RELEASE_VERSION }}
          if [ "${{ steps.latest-release.outputs.release }}" == "$GITHUB_REF_NAME" ]; then
            make docker-build -e VERSION=latest
          fi
      - name: push docker image
        run: |
          make docker-push -e VERSION=${{ env.RELEASE_VERSION }}
          if [ "${{ steps.latest-release.outputs.release }}" == "$GITHUB_REF_NAME" ]; then
            make docker-push -e VERSION=latest
          fi
